### ISSUE TITLE
Local NPM Install Fails

### ISSUE THREAD

**Issue by znewton** [AlaskaAirlines/OrionStatelessComponents__ods-button#10] opened 2019-04-16 22:18 UTC
# Issue report

Running `npm i` in the project locally on windows fails.

## Expected Behavior

`npm i` successfully installs dependencies

## Current Behavior

`npm i` fails to install dependencies. Specifically Chromium
![image](https://user-images.githubusercontent.com/14362200/56247572-152b6780-605a-11e9-96f6-7050bfe41b73.png)

## Possible Solution

- Don't use Windows to develop ODS projects

## Steps to Reproduce (for bugs)

1. Open GitBash (Windows 64bit)
2. Navigate to freshly cloned ODS Button repo
3. Run `npm i`
4. Observe Chromium failed to install

## Context

I wanted to contribute to ODS button, but I can't run locally to verify development changes.

## Your Environment

* Version used: Commit 1e38d96
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Windows 10 (desktop) + Git Bash + Hyper.js
* Link to your project: [OrionStatelessComponents__ods-button](https://github.com/AlaskaAirlines/OrionStatelessComponents__ods-button)

**Comment by blackfalcon** [comment] 2019-04-17 00:07
This is an issue I am digging into. There is an issue with PUPPETEER and installing CHROMIUM. There seem to be scenarios where CHROMIUM fails due to network restrictions. 

There is not a bug in the code. If you choose other than an internal network connection, mac or windows, it will install as expected. 

The only solution I have come up with so far may be related to this issue:
https://github.com/GoogleChrome/puppeteer/issues/2262

**Comment by blackfalcon** [comment] 2019-05-02 18:56
I am going to close this issue as it's been temp resolved by removing this dependency.

**Closed by blackfalcon** 2019-05-02 18:56 UTC
Labels: external issue
